name: PluginStudying
version: '${project.version}'
main: com.paiique.pluginstudying.PluginStudying
api-version: '1.20'
debug: true
commands:
  playerTerrain:
    description: Enables and disables terrain modification.
    usage: /<command> <enable/disable>

  grabTheSun:
    description: Enables and disables sun grabber (???????????????).
    usage: /<command> <grab/release>

  testCommand:
    description: Enables and disables testCommand.
    usage: /<command> <?>
